services:
  - docker

script:
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
  - docker build -t udagram-reverseproxy ./project/udagram-reverseproxy
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker build -t udagram-frontend ./project/udagram-frontend

  # Tagging
  - docker tag udagram-reverseproxy isaacllarbi/reverseproxy:v1
  - docker tag udagram-api-feed isaacllarbi/udagram-api-feed:v1
  - docker tag udagram-api-user isaacllarbi/udagram-api-user:v1
  - docker tag udagram-frontend isaacllarbi/udagram-frontend:v1

after_success:
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push isaacllarbi/reverseproxy:v1 
  - docker push isaacllarbi/udagram-api-feed:v1
  - docker push isaacllarbi/udagram-api-user:v1
  - docker push isaacllarbi/udagram-frontend:v1
